blank_issues_enabled: false
contact_links:
  # - name: Questions & Discussions
  #   url: https://github.com/danwahlin/zingit/discussions
  #   about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/danwahlin/zingit?tab=readme-ov-file#quick-start
    about: Check out the documentation for help getting started
